CREATE_RESULT_BACKEND_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS {} (
    task_id {} UNIQUE,
    result BYTEA
)
"""

CREATE_RESULT_BACKEND_INDEX_QUERY = """
CREATE INDEX IF NOT EXISTS {}_task_id_idx ON {} USING HASH (task_id)
"""

INSERT_RESULT_QUERY = """
INSERT INTO {} VALUES ($1, $2)
"""

IS_RESULT_EXISTS_QUERY = """
SELECT EXISTS(
    SELECT 1 FROM {} WHERE task_id = $1
)
"""

SELECT_RESULT_QUERY = """
SELECT result FROM {} WHERE task_id = $1
"""

DELETE_RESULT_QUERY = """
DELETE FROM {} WHERE task_id = $1
"""


CREATE_SCHEDULE_SOURCE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS {} (
    schedule_id VARCHAR(255) UNIQUE,
    schedule BYTEA
)
"""

CREATE_RESULT_BACKEND_INDEX_QUERY = """
CREATE INDEX IF NOT EXISTS {}_schedule_id_idx ON {} USING HASH (schedule_id)
"""

DELETE_SCHEDULE_QUERY = """
DELETE FROM {} WHERE schedule_id = $1
"""

SELECT_ALL_SCHEDULES = """
SELECT schedule FROM {}
"""
